# Generated by Django 2.0.1 on 2018-01-09 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplify', '0003_auto_20180109_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': '1 - Group', 'verbose_name_plural': '1 - Groups'},
        ),
        migrations.AlterModelOptions(
            name='method',
            options={'verbose_name': '2 - Method', 'verbose_name_plural': '2 - Methods'},
        ),
        migrations.AlterModelOptions(
            name='script',
            options={'verbose_name': '# Script', 'verbose_name_plural': '# Scripts'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '# Task', 'verbose_name_plural': '# Tasks'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'permissions': (('can_use_api', 'Can use API'),), 'verbose_name': '3 - User', 'verbose_name_plural': '3 - Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default='+da_e3E57DE3-89+A0~0_/CFfCDFAe0A', max_length=32, unique=True, validators=[django.core.validators.MaxLengthValidator(32), django.core.validators.MinLengthValidator(10)], verbose_name='Authentication key'),
        ),
    ]
