# Generated by Django 2.0.1 on 2018-01-09 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplify', '0005_auto_20180109_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='method',
            options={'permissions': (('can_read_script', 'Can read script'),), 'verbose_name': '2 - Method', 'verbose_name_plural': '2 - Methods'},
        ),
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default='F9-A60C7~72F~e3B76D1.1b68-Ea7e_b', max_length=32, unique=True, validators=[django.core.validators.MaxLengthValidator(32), django.core.validators.MinLengthValidator(10)], verbose_name='Authentication key'),
        ),
    ]
