# Generated by Django 2.0.1 on 2018-01-09 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplify', '0006_auto_20180109_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='method',
            options={'permissions': (('can_read', 'Can read script'),), 'verbose_name': '2 - Method', 'verbose_name_plural': '2 - Methods'},
        ),
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default='d4B0+C.7Df408/BbD7+fEcc54e5.fC2-', max_length=32, unique=True, validators=[django.core.validators.MaxLengthValidator(32), django.core.validators.MinLengthValidator(10)], verbose_name='Authentication key'),
        ),
    ]
