# Generated by Django 2.0.1 on 2018-01-09 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplify', '0007_auto_20180109_2308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='method',
            options={'permissions': (('can_update', 'Can update script'), ('can_read', 'Can read script')), 'verbose_name': '2 - Method', 'verbose_name_plural': '2 - Methods'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('can_update', 'Can update task'), ('can_read', 'Can read task')), 'verbose_name': '# Task', 'verbose_name_plural': '# Tasks'},
        ),
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default='+C/+bC72cd/F9-9Cdd_.b7-efFe6-~30', max_length=32, unique=True, validators=[django.core.validators.MaxLengthValidator(32), django.core.validators.MinLengthValidator(10)], verbose_name='Authentication key'),
        ),
    ]
