# Generated by Django 2.0.1 on 2018-01-09 23:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplify', '0008_auto_20180109_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='ldap_bind',
            field=models.CharField(blank=True, help_text='Bind for override user permission, ex: cn=manager,dc=domain,dc=com (Keep null if not used)', max_length=254, null=True, verbose_name='Root DN'),
        ),
        migrations.AddField(
            model_name='method',
            name='ldap_define',
            field=models.CharField(blank=True, help_text='Base DN', max_length=254, null=True, verbose_name='Base DN ex: dc=domain,dc=com'),
        ),
        migrations.AddField(
            model_name='method',
            name='ldap_host',
            field=models.CharField(blank=True, default='localhost', help_text='Hostname/IP', max_length=254, null=True, verbose_name='Use hostname or IP address'),
        ),
        migrations.AddField(
            model_name='method',
            name='ldap_password',
            field=models.CharField(blank=True, help_text='Password used by the bind', max_length=254, null=True, verbose_name='Root password'),
        ),
        migrations.AddField(
            model_name='method',
            name='ldap_scope',
            field=models.CharField(choices=[('SCOPE_BASE', 'base (scope=base)'), ('SCOPE_ONELEVEL', 'onelevel (scope=onelevel)'), ('SCOPE_SUBTREE', 'subtree (scope=subtree)')], default='SCOPE_BASE', help_text='Choice a scope. The command will be like "scope=***"', max_length=14, verbose_name='Scope'),
        ),
        migrations.AddField(
            model_name='method',
            name='ldap_search',
            field=models.TextField(blank=True, help_text='search DN (LDAP filter) ex : (&(uid={{tag}})(memberof=cn=my-cn,ou=groups,dc=hub-t,dc=net)) | Available tags: username', null=True, verbose_name='Search DN'),
        ),
        migrations.AddField(
            model_name='method',
            name='ldap_user',
            field=models.TextField(blank=True, help_text='Replace root DN by a User DN. <strong>Do not use with root DN</strong> | user DN ex : uid={{tag}},ou=my-ou,dc=domain,dc=com | Available tags: username', null=True, verbose_name='User DN'),
        ),
        migrations.AddField(
            model_name='method',
            name='ldap_version',
            field=models.CharField(choices=[('VERSION2', 'Version 2 (LDAPv2)'), ('VERSION3', 'Version 3 (LDAPv3)')], default='VERSION3', help_text='Choice a version', max_length=8, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default='Cf7Ea0EDA15bA-E/A~/b2b.7AEd~d2+0', max_length=32, unique=True, validators=[django.core.validators.MaxLengthValidator(32), django.core.validators.MinLengthValidator(10)], verbose_name='Authentication key'),
        ),
    ]
