# Generated by Django 2.0.1 on 2018-01-09 23:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplify', '0009_auto_20180109_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='method',
            field=models.CharField(choices=[('LDAP', 'LDAP')], help_text='Method type', max_length=4, verbose_name='Create method'),
        ),
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default='E~399.19+dbA_.434b_D/8a.fe4feB~.', max_length=32, unique=True, validators=[django.core.validators.MaxLengthValidator(32), django.core.validators.MinLengthValidator(10)], verbose_name='Authentication key'),
        ),
    ]
