# Generated by Django 2.0.1 on 2018-01-10 02:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplify', '0010_auto_20180109_2333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='method',
            options={'permissions': (('can_update', 'Can update task'), ('can_read', 'Can read task'), ('can_check', 'Can check method')), 'verbose_name': '2 - Method', 'verbose_name_plural': '2 - Methods'},
        ),
        migrations.AddField(
            model_name='method',
            name='ldap_tls_cacertfile',
            field=models.BooleanField(default=False, help_text='Set path name of file containing all trusted CA certificates', verbose_name='trusted CA certificates'),
        ),
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default='/a_e+-Ef43_1-BB~DDb6aC-a~cBC5-76', max_length=32, unique=True, validators=[django.core.validators.MaxLengthValidator(32), django.core.validators.MinLengthValidator(10)], verbose_name='Authentication key'),
        ),
    ]
