# Generated by Django 2.0.1 on 2018-01-10 02:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplify', '0011_auto_20180110_0208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='method',
            old_name='ldap_tls_cacertfile',
            new_name='ldap_tls_cacert',
        ),
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default='CF/f_b/e1A2b+07f~eBECafaDDa_7b~c', max_length=32, unique=True, validators=[django.core.validators.MaxLengthValidator(32), django.core.validators.MinLengthValidator(10)], verbose_name='Authentication key'),
        ),
    ]
