# Generated by Django 2.0.1 on 2018-01-10 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplify', '0012_auto_20180110_0208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='method',
            options={'permissions': (('can_read', 'Can read task'), ('can_check', 'Can check method')), 'verbose_name': '2 - Method', 'verbose_name_plural': '2 - Methods'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('can_read', 'Can read task'),), 'verbose_name': '# Task', 'verbose_name_plural': '# Tasks'},
        ),
        migrations.AddField(
            model_name='task',
            name='default',
            field=models.CharField(blank=True, choices=[('purge_tasks', 'Purge tasks'), ('check_methods', 'Check methods'), ('cache_methods', 'Generate method caches')], help_text='Default tasks', max_length=8, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default='_ef_5BeE.DcbaBbD2291D1bC~f4a+c2E', max_length=32, unique=True, validators=[django.core.validators.MaxLengthValidator(32), django.core.validators.MinLengthValidator(10)], verbose_name='Authentication key'),
        ),
    ]
