# Generated by Django 2.0.1 on 2018-01-10 18:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simplify', '0013_auto_20180110_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='script',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='simplify.Script'),
        ),
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default='c77._5b7CB0E4aAfe+c9750A.768cCB2', max_length=32, unique=True, validators=[django.core.validators.MaxLengthValidator(32), django.core.validators.MinLengthValidator(10)], verbose_name='Authentication key'),
        ),
    ]
