# Generated by Django 2.0.1 on 2018-01-10 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplify', '0014_auto_20180110_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default='8126EFE9A9cb5./c81fF9d27fB23D4fe', max_length=32, unique=True, validators=[django.core.validators.MaxLengthValidator(32), django.core.validators.MinLengthValidator(10)], verbose_name='Authentication key'),
        ),
    ]
