# Generated by Django 2.0.1 on 2018-01-10 18:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simplify', '0015_auto_20180110_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='default',
            field=models.CharField(blank=True, choices=[('purge_tasks', 'Purge tasks'), ('check_methods', 'Check methods'), ('cache_methods', 'Generate method caches')], help_text='Default tasks', max_length=13, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simplify.Script'),
        ),
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default='b5_a~9cE0C9/Ebf4Ba/e6C_8-f9-Ce3b', max_length=32, unique=True, validators=[django.core.validators.MaxLengthValidator(32), django.core.validators.MinLengthValidator(10)], verbose_name='Authentication key'),
        ),
    ]
