# Generated by Django 2.0.1 on 2018-01-10 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplify', '0016_auto_20180110_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='script',
            field=models.CharField(default='test', help_text='Script filename without extension .py', max_length=254, verbose_name='Script filename'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default='ED3E78DA1d/~EA3Dba89.dFC3/E0_a_F', max_length=32, unique=True, validators=[django.core.validators.MaxLengthValidator(32), django.core.validators.MinLengthValidator(10)], verbose_name='Authentication key'),
        ),
    ]
