# Generated by Django 2.0.1 on 2018-01-10 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplify', '0017_auto_20180110_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='name',
            field=models.CharField(help_text='Script name', max_length=254, unique=True, verbose_name='Script name'),
        ),
        migrations.AlterField(
            model_name='script',
            name='script',
            field=models.CharField(help_text='Script filename without extension .py', max_length=254, unique=True, verbose_name='Script filename'),
        ),
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default='C89AFc.a4-bc2D63007fe.0edc3E66DD', max_length=32, unique=True, validators=[django.core.validators.MaxLengthValidator(32), django.core.validators.MinLengthValidator(10)], verbose_name='Authentication key'),
        ),
    ]
