# Generated by Django 2.0.1 on 2018-01-10 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplify', '0018_auto_20180110_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='method',
            options={'permissions': (('can_read_method', 'Can read task'), ('can_check_method', 'Can check method')), 'verbose_name': '2 - Method', 'verbose_name_plural': '2 - Methods'},
        ),
        migrations.AlterModelOptions(
            name='script',
            options={'permissions': (('can_read_script', 'Can read task'),), 'verbose_name': '# Script', 'verbose_name_plural': '# Scripts'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('can_read_task', 'Can read task'),), 'verbose_name': '# Task', 'verbose_name_plural': '# Tasks'},
        ),
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default='c17b+E7+9c~_~31B+4/b0.52dF+__cAd', max_length=32, unique=True, validators=[django.core.validators.MaxLengthValidator(32), django.core.validators.MinLengthValidator(10)], verbose_name='Authentication key'),
        ),
    ]
