# Generated by Django 2.0.1 on 2018-01-10 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplify', '0019_auto_20180110_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='script',
            options={'permissions': (('can_read_script', 'Can read script'),), 'verbose_name': '# Script', 'verbose_name_plural': '# Scripts'},
        ),
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default='0d073E2f0Dff4C383A95d02e5bBBEd6-', max_length=32, unique=True, validators=[django.core.validators.MaxLengthValidator(32), django.core.validators.MinLengthValidator(10)], verbose_name='Authentication key'),
        ),
    ]
